# Generated by Django 5.0.1 on 2024-01-27 04:29

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Agent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("mobile", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=254)),
                ("reference", models.CharField(max_length=255)),
                (
                    "profile_picture",
                    models.ImageField(
                        blank=True, null=True, upload_to="agent_profiles/"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Amenity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Feature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "latitude",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(-90),
                            django.core.validators.MaxValueValidator(90),
                        ]
                    ),
                ),
                (
                    "longitude",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(-180),
                            django.core.validators.MaxValueValidator(180),
                        ]
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SurfaceArea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("built", models.IntegerField()),
                ("plot", models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Property",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField()),
                ("property_purpose", models.CharField(max_length=255)),
                ("ref", models.CharField(max_length=20, unique=True)),
                ("price", models.IntegerField()),
                ("currency", models.CharField(max_length=10)),
                ("price_freq", models.CharField(max_length=10)),
                ("property_type", models.CharField(max_length=255)),
                ("sub_location", models.TextField()),
                ("town", models.CharField(max_length=100)),
                ("province", models.CharField(max_length=100)),
                ("country", models.CharField(max_length=100)),
                ("location_detail", models.TextField()),
                ("title", models.TextField()),
                ("beds", models.IntegerField()),
                ("baths", models.IntegerField()),
                ("video_url", models.URLField(blank=True, null=True)),
                ("description", models.TextField()),
                (
                    "agent",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="listings.agent",
                    ),
                ),
                ("amenities", models.ManyToManyField(to="listings.amenity")),
                ("features", models.ManyToManyField(to="listings.feature")),
                ("images", models.ManyToManyField(to="listings.image")),
                (
                    "location",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="listings.location",
                    ),
                ),
                (
                    "surface_area",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="listings.surfacearea",
                    ),
                ),
            ],
        ),
    ]
