# Generated by Django 5.0.1 on 2024-02-12 04:56

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Property",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.CharField(max_length=255)),
                ("property_purpose", models.CharField(max_length=255)),
                ("ref", models.CharField(max_length=255)),
                ("price", models.CharField(max_length=255)),
                ("currency", models.CharField(max_length=10)),
                ("price_freq", models.CharField(max_length=255)),
                ("type", models.CharField(max_length=255)),
                ("sub_location", models.TextField()),
                ("town", models.CharField(max_length=255)),
                ("province", models.CharField(max_length=255)),
                ("country", models.CharField(max_length=255)),
                ("latitude", models.CharField(max_length=255)),
                ("longitude", models.CharField(max_length=255)),
                ("location_detail", models.TextField()),
                ("title", models.TextField()),
                ("beds", models.CharField(blank=True, max_length=255, null=True)),
                ("baths", models.CharField(blank=True, max_length=255, null=True)),
                ("built_area", models.CharField(blank=True, max_length=255, null=True)),
                ("plot_area", models.CharField(blank=True, max_length=255, null=True)),
                ("video_url", models.CharField(blank=True, max_length=255, null=True)),
                ("description", models.TextField()),
                ("agent_name", models.CharField(max_length=255)),
                ("agent_mobile", models.CharField(max_length=20)),
                ("agent_email", models.EmailField(max_length=254)),
                ("agent_reference", models.CharField(max_length=255)),
                (
                    "agent_profile_picture",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("images", models.TextField()),
                ("features", models.TextField()),
                ("amenities", models.TextField()),
            ],
            options={
                "verbose_name_plural": "Properties",
            },
        ),
    ]
