# Generated by Django 5.0.1 on 2024-01-30 19:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("listings", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="built_area",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="property",
            name="plot_area",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
