# Generated by Django 5.0.1 on 2024-01-30 19:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("listings", "0002_alter_property_built_area_alter_property_plot_area"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="baths",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="property",
            name="beds",
            field=models.CharField(blank=True, null=True),
        ),
    ]
