# Generated by Django 5.0.1 on 2024-01-30 19:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("listings", "0003_alter_property_baths_alter_property_beds"),
    ]

    operations = [
        migrations.RenameField(
            model_name="property",
            old_name="image",
            new_name="images",
        ),
    ]
