# Generated by Django 5.0.1 on 2024-01-30 20:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("listings", "0004_rename_image_property_images"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="property",
            options={"verbose_name_plural": "Properties"},
        ),
    ]
